import { AlertTriangle, Download, Flag, MoreHorizontal, Search, TimerReset } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Badge, Metric, Panel, SectionTitle } from '../components/Shared'
import { Complaint, getComplaints, number } from '../lib/api'

export function Admin() {
  const [complaints, setComplaints] = useState<Complaint[]>([]); const [filter, setFilter] = useState('all')
  useEffect(() => { getComplaints().then(result => setComplaints(result.items)) }, [])
  const demo = complaints.length ? complaints : [{ complaint_id: 'GR-017821', text: 'Water comes only for one hour and is muddy', category: 'water', urgency: 'urgent', confidence: .91, expected_resolution_days: 2, status: 'breach' }, { complaint_id: 'GR-017824', text: 'Garbage has not been collected for four days', category: 'waste', urgency: 'standard', confidence: .86, expected_resolution_days: 7, status: 'assigned' }, { complaint_id: 'GR-017826', text: 'The lane is dark and unsafe for women', category: 'safety', urgency: 'urgent', confidence: .82, expected_resolution_days: 2, status: 'received' }, { complaint_id: 'GR-017830', text: 'SRA survey has not happened', category: 'housing', urgency: 'standard', confidence: .79, expected_resolution_days: 7, status: 'assigned' }] as Complaint[]
  const filtered = demo.filter(item => filter === 'all' || item.urgency === filter)
  return <div className="page-pad"><SectionTitle eyebrow="Officer workspace · synthetic queue" title="Grievance command centre" description="Prioritise urgency, see SLA risk and export a clean handoff to ward teams." action={<button className="button outline"><Download size={15} /> Export CSV</button>} /><div className="admin-metrics"><Metric label="Open queue" value={number(demo.length)} note="across 9 demo wards" icon={<Flag size={18} />} color="blue" /><Metric label="SLA breaches" value="12" note="needs escalation today" icon={<AlertTriangle size={18} />} color="red" /><Metric label="Urgent" value={number(demo.filter(x => x.urgency === 'urgent').length)} note="predicted priority" icon={<TimerReset size={18} />} color="amber" /><Metric label="Median response" value="4.2d" note="last 30-day demo view" icon={<TimerReset size={18} />} /></div><Panel title="Triage queue" subtitle="Sorted by urgency × time at risk" action={<div className="queue-actions"><div className="search-box compact"><Search size={14} /><input placeholder="Find complaint" /></div><select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All urgency</option><option value="urgent">Urgent</option><option value="standard">Standard</option></select><button className="icon-button" aria-label="More filters"><MoreHorizontal size={18} /></button></div>}><div className="table-scroll"><table><thead><tr><th>Complaint</th><th>Classification</th><th>SLA target</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(item => <tr key={item.complaint_id}><td><b>{item.complaint_id}</b><span>{item.text}</span></td><td><Badge tone={item.urgency === 'urgent' ? 'red' : 'teal'}>{item.urgency}</Badge><small>{item.category} · {Math.round(item.confidence * 100)}% confidence</small></td><td><b>{item.expected_resolution_days} days</b><small>from receipt</small></td><td><span className={`status-text ${item.status === 'breach' ? 'red-text' : ''}`}><i /> {item.status}</span></td><td><button className="text-button">Assign <MoreHorizontal size={14} /></button></td></tr>)}</tbody></table></div><div className="table-footer">Showing {filtered.length} rows · Predictions support officers; they do not decide disposition.</div></Panel><div className="admin-note"><AlertTriangle size={16} /><span><b>Data minimisation:</b> the officer queue uses a complaint reference and location linkage; direct resident identifiers should remain in the approved grievance system.</span></div></div>
}
