import { AlertTriangle, Download, Flag, MoreHorizontal, Search, TimerReset } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Badge, Metric, Panel, SectionTitle } from '../components/Shared'
import { useI18n } from '../i18n'
import { Complaint, getComplaints, number } from '../lib/api'

export function Admin() {
  const { t } = useI18n()
  const [complaints, setComplaints] = useState<Complaint[]>([]); const [filter, setFilter] = useState('all'); const [search, setSearch] = useState('')
  useEffect(() => { getComplaints().then(result => setComplaints(result.items)) }, [])
  const demo = complaints.length ? complaints : [{ complaint_id: 'GR-017821', text: t('demoWaterComplaint'), category: 'water', urgency: 'urgent', confidence: .91, expected_resolution_days: 2, status: 'breach' }, { complaint_id: 'GR-017824', text: t('demoWasteComplaint'), category: 'waste', urgency: 'standard', confidence: .86, expected_resolution_days: 7, status: 'assigned' }, { complaint_id: 'GR-017826', text: t('demoSafetyComplaint'), category: 'safety', urgency: 'urgent', confidence: .82, expected_resolution_days: 2, status: 'received' }, { complaint_id: 'GR-017830', text: t('demoHousingComplaint'), category: 'housing', urgency: 'standard', confidence: .79, expected_resolution_days: 7, status: 'assigned' }] as Complaint[]
  const categoryLabels: Record<string, string> = { water: t('waterLabel'), sanitation: t('sanitationLabel'), power: t('powerLabel'), waste: t('wasteLabel'), drainage: t('drainageLabel'), health: t('healthLabel'), safety: t('safetyLabel'), housing: t('housingLabel') }
  const urgencyLabels: Record<string, string> = { urgent: t('urgentStatus'), standard: t('standardStatus') }
  const statusLabels: Record<string, string> = { received: t('receivedStatus'), assigned: t('assignedStatus'), breach: t('breachStatus') }
  const filtered = demo.filter(item => (filter === 'all' || item.urgency === filter) && `${item.complaint_id} ${item.text} ${item.category}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="page-pad"><SectionTitle eyebrow={t('officerWorkspace')} title={t('commandCentre')} description={t('commandDesc')} action={<button className="button outline"><Download size={15} /> {t('exportCsv')}</button>} /><div className="admin-metrics"><Metric label={t('openQueue')} value={number(demo.length)} note={t('acrossWards')} icon={<Flag size={18} />} color="blue" /><Metric label={t('slaBreaches')} value="12" note={t('escalationToday')} icon={<AlertTriangle size={18} />} color="red" /><Metric label={t('urgent')} value={number(demo.filter(x => x.urgency === 'urgent').length)} note={t('predictedPriority')} icon={<TimerReset size={18} />} color="amber" /><Metric label={t('medianResponse')} value="4.2d" note={t('last30Days')} icon={<TimerReset size={18} />} /></div><Panel title={t('triageQueue')} subtitle={t('sortedUrgency')} action={<div className="queue-actions"><div className="search-box compact"><Search size={14} /><input aria-label={t('findComplaint')} placeholder={t('findComplaint')} value={search} onChange={e => setSearch(e.target.value)} /></div><select aria-label={t('allUrgency')} value={filter} onChange={e => setFilter(e.target.value)}><option value="all">{t('allUrgency')}</option><option value="urgent">{t('urgent')}</option><option value="standard">{t('standard')}</option></select><button className="icon-button" aria-label={t('moreFilters')}><MoreHorizontal size={18} /></button></div>}><div className="table-scroll"><table><thead><tr><th>{t('complaint')}</th><th>{t('classification')}</th><th>{t('slaTarget')}</th><th>{t('status')}</th><th>{t('action')}</th></tr></thead><tbody>{filtered.map(item => <tr key={item.complaint_id}><td><b>{item.complaint_id}</b><span>{item.text}</span></td><td><Badge tone={item.urgency === 'urgent' ? 'red' : 'teal'}>{urgencyLabels[item.urgency] || item.urgency}</Badge><small>{categoryLabels[item.category] || item.category} · {Math.round(item.confidence * 100)}% {t('confidence')}</small></td><td><b>{item.expected_resolution_days} {t('days')}</b><small>{t('fromReceipt')}</small></td><td><span className={`status-text ${item.status === 'breach' ? 'red-text' : ''}`}><i /> {statusLabels[item.status] || item.status}</span></td><td><button className="text-button">{t('assign')} <MoreHorizontal size={14} /></button></td></tr>)}</tbody></table></div><div className="table-footer">{t('showingRows', { count: filtered.length })}</div></Panel><div className="admin-note"><AlertTriangle size={16} /><span><b>{t('dataMinimisation')}</b> {t('officerPrivacy')}</span></div></div>
}
