import { AlertTriangle, CheckCircle2, CircleDot, Droplets, Gauge, Trash2, Zap } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Badge, Panel, SectionTitle } from '../components/Shared'
import { Pocket } from '../lib/api'

export function Assurance({ pockets, onSelect }: { pockets: Pocket[]; onSelect: (id: string) => void }) {
  const wards = ['L Ward', 'Thane West', 'Kalyan East', 'Ulhasnagar', 'S Ward']; const data = wards.map((ward, i) => ({ ward: ward.replace(' Ward', ''), compliance: [58, 71, 62, 76, 67][i], gaps: [43, 28, 36, 19, 30][i] }))
  return <div className="page-pad"><SectionTitle eyebrow="Post-handover accountability" title="Service assurance tracker" description="A simple SLA view: what residents should receive, what the data says, and where to intervene next." action={<div className="status-pill"><span className="live-dot" /> Last refresh · demo now</div>} /><div className="assurance-metrics"><div className="assurance-score"><Gauge size={21} /><span>MMR average</span><strong>63.8</strong><small>assurance / 100</small></div><div className="assurance-stat"><CheckCircle2 size={18} /><b>61%</b><span>within SLA today</span></div><div className="assurance-stat warning"><AlertTriangle size={18} /><b>547</b><span>gaps need follow-up</span></div><div className="assurance-stat"><CircleDot size={18} /><b>14</b><span>wards monitored</span></div></div><div className="assurance-grid"><Panel title="Service-level scorecards" subtitle="Click a pocket to open its evidence"><div className="scorecard-list">{pockets.slice(0, 7).map((p, i) => <button className="scorecard" key={p.pocket_id} onClick={() => onSelect(p.pocket_id)}><div className="scorecard-id"><span className={`traffic ${i < 3 ? 'red' : i === 3 ? 'amber' : 'green'}`} /> <b>{p.pocket_id}</b><small>{p.ward}</small></div><div className="score-item"><Droplets size={14} /><span>Water</span><b>{Math.round(p.water_hours_per_day / 12 * 100)}</b></div><div className="score-item"><Trash2 size={14} /><span>Waste</span><b>{Math.round(p.waste_collection_frequency / 7 * 100)}</b></div><div className="score-item"><Zap size={14} /><span>Power</span><b>{Math.round(100 - p.outage_hours_per_week / 24 * 100)}</b></div><div className="score-arrow">→</div></button>)}</div></Panel><Panel title="Ward accountability board" subtitle="Compliance ranking · illustrative"><ResponsiveContainer width="100%" height={290}><BarChart data={data} layout="vertical" margin={{ left: 20, right: 20 }}><CartesianGrid horizontal={false} stroke="#e6edeb" /><XAxis type="number" domain={[0, 100]} tickFormatter={v => `${v}%`} tick={{ fontSize: 11 }} /><YAxis type="category" dataKey="ward" tick={{ fontSize: 11 }} width={62} /><Tooltip formatter={(v: number) => `${v}%`} /><Bar dataKey="compliance" fill="#159d9a" radius={[0, 5, 5, 0]} barSize={18} /></BarChart></ResponsiveContainer><div className="accountability-callout"><span className="live-dot" /> Ulhasnagar is leading this demo cohort at 76% SLA compliance.</div></Panel></div><div className="footnote">Minimum standards shown here are demo rules: water ≥ 4 hours/day, toilets ≥ 15/100 people, outages ≤ 12 hours/week and waste collection ≥ 3/week.</div></div>
}
