import { Filter, ListFilter, MapPinned, Search, SlidersHorizontal, Waves } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Badge, Metric, Panel, PocketMap, SectionTitle, tierColors } from '../components/Shared'
import { useI18n } from '../i18n'
import { Pocket, Summary, number } from '../lib/api'

export function Dashboard({ pockets, summary, onSelect }: { pockets: Pocket[]; summary: Summary; onSelect: (id: string) => void }) {
  const { t } = useI18n()
  const [city, setCity] = useState('All cities'); const [tier, setTier] = useState('All tiers'); const [heat, setHeat] = useState('priority'); const [search, setSearch] = useState('')
  const cities = [{ value: 'Mumbai', label: t('cityMumbai') }, { value: 'Thane', label: t('cityThane') }, { value: 'Kalyan', label: t('cityKalyan') }, { value: 'Ambarnath', label: t('cityAmbarnath') }, { value: 'Ulhasnagar', label: t('cityUlhasnagar') }]
  const tiers = [{ value: 'Critical', label: t('tier.critical') }, { value: 'High', label: t('tier.high') }, { value: 'Medium', label: t('tier.medium') }, { value: 'Low', label: t('tier.low') }]
  const filtered = useMemo(() => pockets.filter(p => (city === 'All cities' || p.city === city) && (tier === 'All tiers' || p.tier === tier) && `${p.pocket_id} ${p.ward} ${p.city}`.toLowerCase().includes(search.toLowerCase())), [pockets, city, tier, search])
  const top = [...filtered].sort((a, b) => b.priority_score - a.priority_score).slice(0, 6)
  const cityLabel = (value: string) => t(`city${value}`)
  return <div className="page-pad"><SectionTitle eyebrow={t('decisionCockpit')} title={t('priorityMap')} description={t('dashboardDesc')} action={<div className="status-pill"><span className="live-dot" /> {t('modelReady')}</div>} /><div className="dashboard-grid"><div className="dashboard-main"><div className="map-toolbar"><div className="search-box"><Search size={16} /><input aria-label={t('searchPockets')} placeholder={t('searchPockets')} value={search} onChange={e => setSearch(e.target.value)} /></div><div className="select-wrap"><Filter size={14} /><select value={city} onChange={e => setCity(e.target.value)}><option value="All cities">{t('allCities')}</option>{cities.map(x => <option value={x.value} key={x.value}>{x.label}</option>)}</select></div><div className="select-wrap"><SlidersHorizontal size={14} /><select value={tier} onChange={e => setTier(e.target.value)}><option value="All tiers">{t('allTiers')}</option>{tiers.map(x => <option value={x.value} key={x.value}>{x.label}</option>)}</select></div><div className="heat-switch"><button className={heat === 'priority' ? 'active' : ''} onClick={() => setHeat('priority')}>{t('priority')}</button><button className={heat === 'flood' ? 'active' : ''} onClick={() => setHeat('flood')}>{t('flood')}</button><button className={heat === 'fire' ? 'active' : ''} onClick={() => setHeat('fire')}>{t('fire')}</button><button className={heat === 'services' ? 'active' : ''} onClick={() => setHeat('services')}>{t('service')}</button></div></div><PocketMap pockets={filtered} onSelect={onSelect} mode={heat} /></div><aside className="dashboard-side"><Panel title={t('situationRoom')} subtitle={t('modelSignals')}><div className="side-kpis"><div><strong>{number(filtered.length)}</strong><span>{t('shownOnMap')}</span></div><div><strong>{number(summary.critical_pockets)}</strong><span>{t('criticalPockets')}</span></div><div><strong>63.8</strong><span>{t('avgAssurance')}</span></div></div><div className="divider" /><div className="eyebrow">{t('topQueue')}</div><div className="rank-list">{top.map((p, i) => <button className="rank-item" key={p.pocket_id} onClick={() => onSelect(p.pocket_id)}><b>{String(i + 1).padStart(2, '0')}</b><div><strong>{p.pocket_id}</strong><span>{cityLabel(p.city)} · {p.ward}</span></div><div className="rank-score" style={{ color: tierColors[p.tier] }}>{p.priority_score.toFixed(1)}</div></button>)}</div><button className="button outline full"><ListFilter size={15} /> {t('openRankedQueue')}</button></Panel><Panel title={t('readMap')} className="map-help"><p><MapPinned size={16} /> {t('clickDot')}</p><p><Waves size={16} /> {t('useHeatmap')}</p><div className="land-legend"><span><i className="land state" /> {t('state')}</span><span><i className="land private" /> {t('private')}</span><span><i className="land railway" /> {t('railway')}</span></div></Panel></aside></div><div className="footnote">{t('showingPockets', { count: number(filtered.length) })}</div></div>
}
