import { ArrowRight, CheckCircle2, CircleDollarSign, Droplets, House, Map, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { Metric, Panel, Badge, Note } from '../components/Shared'
import { useI18n } from '../i18n'
import { Summary, number, money } from '../lib/api'

export function Landing({ summary, onOpen }: { summary: Summary; onOpen: (page: string) => void }) {
  const { t } = useI18n()
  return <div className="landing page-pad">
    <div className="hero-grid"><div className="hero-copy"><Badge tone="amber"><Sparkles size={13} /> {t('aiResidentVoice')}</Badge><h1>{t('planSaferHomes')}<br /><em>{t('proveServicesArrive')}</em></h1><p className="hero-lede">{t('landingLead')}</p><div className="hero-actions"><button className="button primary" onClick={() => onOpen('dashboard')}>{t('explorePriorityMap')} <ArrowRight size={17} /></button><button className="button ghost" onClick={() => onOpen('resident')}>{t('checkEligibility')}</button></div><div className="trust-row"><span><CheckCircle2 size={15} /> {t('humanLoop')}</span><span><CheckCircle2 size={15} /> {t('multilingual')}</span><span><CheckCircle2 size={15} /> {t('syntheticData')}</span></div></div><div className="hero-art"><div className="orb orb-one" /><div className="orb orb-two" /><div className="city-card card"><div className="city-card-top"><span className="live-dot" /> {t('mmrServicePulse')} <span className="tiny-label">{t('liveDemo')}</span></div><div className="pulse-score">63<span>/100</span></div><div className="pulse-label">{t('averageAssurance')}</div><div className="pulse-bars"><i style={{ width: '78%' }} /><i style={{ width: '54%' }} /><i style={{ width: '66%' }} /><i style={{ width: '41%' }} /></div><div className="mini-map"><span className="mini-dot red" /><span className="mini-dot amber" /><span className="mini-dot teal" /><span className="mini-dot blue" /></div></div><div className="float-card float-one"><Map size={18} /><div><b>{number(summary.pockets_prioritised)}</b><small>{t('pocketsScreened')}</small></div></div><div className="float-card float-two"><ShieldCheck size={18} /><div><b>{number(summary.service_gaps_flagged)}</b><small>{t('serviceGapsFlagged')}</small></div></div></div></div>
    <div className="impact-grid"><Metric label={t('pocketsPrioritised')} value={number(summary.pockets_prioritised)} note={t('mmrScreening')} icon={<Map size={19} />} color="blue" /><Metric label={t('householdsInView')} value={number(summary.households_covered)} note={t('syntheticPopulation')} icon={<Users size={19} />} color="teal" /><Metric label={t('gapsFlagged')} value={number(summary.service_gaps_flagged)} note={t('assuranceWatchlist')} icon={<Droplets size={19} />} color="amber" /><Metric label={t('avoidableCostSignal')} value={money(summary.projected_cost_saved_inr)} note={t('planningScenario')} icon={<CircleDollarSign size={19} />} color="red" /></div>
    <div className="how-section"><div className="section-heading"><div><div className="eyebrow">{t('fromSignal')}</div><h2>{t('fourDecisions')}</h2><p>{t('designedFor')}</p></div><button className="text-button" onClick={() => onOpen('methodology')}>{t('seeMethodology')} <ArrowRight size={15} /></button></div><div className="steps">{[['01', t('prioritise'), t('prioritiseDesc'), <Map />], ['02', t('plan'), t('planDesc'), <House />], ['03', t('simulate'), t('simulateDesc'), <CircleDollarSign />], ['04', t('assure'), t('assureDesc'), <ShieldCheck />]].map(([n, title, copy, icon]) => <div className="step" key={String(n)}><div className="step-number">{n}</div><div className="step-icon">{icon}</div><h3>{String(title)}</h3><p>{String(copy)}</p></div>)}</div></div>
    <Panel className="sdg-panel"><div className="sdg-copy"><Badge>{t('policyAligned')}</Badge><h2>{t('builtForSystems')}</h2><p>{t('policyDesc')}</p><Note>{t('syntheticNotice')}</Note></div><div className="sdg-badges"><div><b>6</b><span>{t('cleanWater')}</span></div><div><b>11</b><span>{t('sustainableCities')}</span></div><div><b>PMAY</b><span>{t('housingForAll')}</span></div><div><b>SRA</b><span>{t('insituPathways')}</span></div></div></Panel>
  </div>
}
