import { ArrowRight, CheckCircle2, CircleDollarSign, Droplets, House, Map, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { Metric, Panel, Badge, Note } from '../components/Shared'
import { Summary, number, money } from '../lib/api'

export function Landing({ summary, onOpen }: { summary: Summary; onOpen: (page: string) => void }) {
  return <div className="landing page-pad">
    <div className="hero-grid"><div className="hero-copy"><Badge tone="amber"><Sparkles size={13} /> AI + resident voice</Badge><h1>Plan safer homes.<br /><em>Prove services arrive.</em></h1><p className="hero-lede">NagarSeva turns fragmented city signals into a transparent, resident-first plan for affordable housing, slum redevelopment and everyday service assurance across the Mumbai Metropolitan Region.</p><div className="hero-actions"><button className="button primary" onClick={() => onOpen('dashboard')}>Explore the priority map <ArrowRight size={17} /></button><button className="button ghost" onClick={() => onOpen('resident')}>Check eligibility</button></div><div className="trust-row"><span><CheckCircle2 size={15} /> Human-in-the-loop</span><span><CheckCircle2 size={15} /> Multilingual by design</span><span><CheckCircle2 size={15} /> Synthetic demo data</span></div></div><div className="hero-art"><div className="orb orb-one" /><div className="orb orb-two" /><div className="city-card card"><div className="city-card-top"><span className="live-dot" /> MMR service pulse <span className="tiny-label">LIVE DEMO</span></div><div className="pulse-score">63<span>/100</span></div><div className="pulse-label">average assurance index</div><div className="pulse-bars"><i style={{ width: '78%' }} /><i style={{ width: '54%' }} /><i style={{ width: '66%' }} /><i style={{ width: '41%' }} /></div><div className="mini-map"><span className="mini-dot red" /><span className="mini-dot amber" /><span className="mini-dot teal" /><span className="mini-dot blue" /></div></div><div className="float-card float-one"><Map size={18} /><div><b>1,500</b><small>pockets screened</small></div></div><div className="float-card float-two"><ShieldCheck size={18} /><div><b>547</b><small>service gaps flagged</small></div></div></div></div>
    <div className="impact-grid"><Metric label="Pockets prioritised" value={number(summary.pockets_prioritised)} note="MMR screening universe" icon={<Map size={19} />} color="blue" /><Metric label="Households in view" value={number(summary.households_covered)} note="synthetic population estimate" icon={<Users size={19} />} color="teal" /><Metric label="Gaps flagged" value={number(summary.service_gaps_flagged)} note="90-day assurance watchlist" icon={<Droplets size={19} />} color="amber" /><Metric label="Avoidable cost signal" value={money(summary.projected_cost_saved_inr)} note="planning scenario only" icon={<CircleDollarSign size={19} />} color="red" /></div>
    <div className="how-section"><div className="section-heading"><div><div className="eyebrow">From signal to seva</div><h2>Four decisions, one accountable loop.</h2><p>Designed for officers, residents and implementation partners to see the same evidence.</p></div><button className="text-button" onClick={() => onOpen('methodology')}>See methodology <ArrowRight size={15} /></button></div><div className="steps">{[['01', 'Prioritise', 'Find pockets where vulnerability, hazard and service deficits overlap.', <Map />], ['02', 'Plan', 'Compare in-situ, upgrading, relocation and rental pathways with reasons.', <House />], ['03', 'Simulate', 'Test FSI, cross-subsidy, cost and market assumptions before a DPR.', <CircleDollarSign />], ['04', 'Assure', 'Track water, sanitation, power, waste and grievances after handover.', <ShieldCheck />]].map(([n, title, copy, icon]) => <div className="step" key={String(n)}><div className="step-number">{n}</div><div className="step-icon">{icon}</div><h3>{String(title)}</h3><p>{String(copy)}</p></div>)}</div></div>
    <Panel className="sdg-panel"><div className="sdg-copy"><Badge>Policy aligned</Badge><h2>Built for the public systems already in motion.</h2><p>Maps the AI workflow to PMAY-Urban, Maharashtra SRA, SBM-Urban, AMRUT, Jal Jeevan Mission, SDG 6 and SDG 11 — so recommendations can enter existing decision cycles.</p><Note>Synthetic, calibrated data is used in this demo. Replace with approved ward, asset and resident-consent data before operational use.</Note></div><div className="sdg-badges"><div><b>6</b><span>Clean water & sanitation</span></div><div><b>11</b><span>Sustainable cities</span></div><div><b>PMAY</b><span>Housing for all</span></div><div><b>SRA</b><span>In-situ pathways</span></div></div></Panel>
  </div>
}
