import { BookOpen, CheckCircle2, Database, Fingerprint, GitBranch, Scale, ShieldCheck, Users } from 'lucide-react'
import { Badge, Note, Panel, SectionTitle } from '../components/Shared'
import { useI18n } from '../i18n'

export function Methodology() {
  const { t } = useI18n()
  const cards = [[t('priorityScore'), t('priorityModel'), 'R² 0.981 · MAE 1.72 · rank correlation 0.994'], [t('interventionModel'), t('interventionModelDesc'), 'Macro-F1 0.760 · confusion matrix exported'], [t('serviceGapModel'), t('serviceGapModelDesc'), 'F1 0.890 · ROC-AUC 0.954'], [t('grievanceNlp'), t('grievanceNlpDesc'), 'Macro-F1 1.000 on template demo split']]
  return <div className="page-pad"><SectionTitle eyebrow={t('methodologyEyebrow')} title={t('methodologyTitle')} description={t('methodologyDesc')} action={<Badge><BookOpen size={14} /> {t('modelCards')}</Badge>} /><div className="method-hero"><div><h2>{t('aiDecides')}</h2><p>{t('methodologyHero')}</p></div><div className="method-icons"><div><Users /><span>{t('residentVoice')}</span></div><div><Scale /><span>{t('fairnessChecks')}</span></div><div><ShieldCheck /><span>{t('dataMin')}</span></div></div></div><div className="method-grid"><Panel title={t('modelCards')} subtitle={t('syntheticHoldout')}><div className="model-card-list">{cards.map(([name, method, metric]) => <div key={name}><div className="model-card-icon"><GitBranch size={17} /></div><div><b>{name}</b><span>{method}</span><small>{metric}</small></div><CheckCircle2 size={16} /></div>)}</div></Panel><Panel title={t('fairnessLimitations')}><div className="limitations"><div><Scale size={16} /><p><b>{t('wardSplit')}</b> {t('wardSplitDesc')}</p></div><div><Database size={16} /><p><b>{t('syntheticCalibration')}</b> {t('syntheticCalibrationDesc')}</p></div><div><Fingerprint size={16} /><p><b>{t('privacyApproach')}</b> {t('privacyDesc')}</p></div></div></Panel></div><Panel title={t('policyBridge')} subtitle={t('policyBridgeDesc')}><div className="policy-chips"><span>PMAY-Urban</span><span>Maharashtra SRA</span><span>SBM-Urban</span><span>AMRUT</span><span>Jal Jeevan Mission</span><span>SDG 6</span><span>SDG 11</span></div><Note>{t('realDataPlug')}</Note></Panel></div>
}
